from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.style import WD_STYLE_TYPE
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / 'output'
OUT.mkdir(exist_ok=True)
DOCX = OUT / 'Fanimation_eProject_Report.docx'

doc = Document()
sec = doc.sections[0]
sec.top_margin = Inches(0.8); sec.bottom_margin = Inches(0.75)
sec.left_margin = Inches(0.8); sec.right_margin = Inches(0.8)

# Theme and professional report styles (narrative_proposal preset, adapted for an academic report).
styles = doc.styles
normal = styles['Normal']; normal.font.name = 'Calibri'; normal._element.rPr.rFonts.set(qn('w:eastAsia'), 'Calibri'); normal.font.size = Pt(10.5)
normal.paragraph_format.space_after = Pt(7); normal.paragraph_format.line_spacing = 1.2
for name, size, colour, before, after in [('Heading 1',16,'2E74B5',18,9),('Heading 2',13,'2E74B5',12,6),('Heading 3',11.5,'1F4D78',8,4)]:
    st=styles[name]; st.font.name='Calibri'; st._element.rPr.rFonts.set(qn('w:eastAsia'),'Calibri'); st.font.size=Pt(size); st.font.bold=True; st.font.color.rgb=RGBColor.from_string(colour); st.paragraph_format.space_before=Pt(before); st.paragraph_format.space_after=Pt(after); st.paragraph_format.keep_with_next=True
caption = styles['Caption']; caption.font.name='Calibri'; caption.font.size=Pt(9); caption.font.italic=True; caption.font.color.rgb=RGBColor(89,89,89); caption.paragraph_format.space_after=Pt(8)

def shade(cell, fill):
    tcPr=cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def set_cell_text(cell, text, bold=False, size=9):
    cell.text=''; p=cell.paragraphs[0]; p.paragraph_format.space_after=Pt(0); r=p.add_run(str(text)); r.bold=bold; r.font.size=Pt(size); cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def table(headers, rows, widths=None):
    t=doc.add_table(rows=1, cols=len(headers)); t.style='Table Grid'; t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for i,h in enumerate(headers): set_cell_text(t.rows[0].cells[i],h,True); shade(t.rows[0].cells[i],'E8EEF5')
    for row in rows:
        cells=t.add_row().cells
        for i,val in enumerate(row): set_cell_text(cells[i],val)
    if widths:
        for row in t.rows:
            for i,w in enumerate(widths): row.cells[i].width=Inches(w)
    doc.add_paragraph('')
    return t
def p(text='', style=None, boldlead=None):
    para=doc.add_paragraph(style=style)
    if boldlead and text.startswith(boldlead):
        para.add_run(boldlead).bold=True; para.add_run(text[len(boldlead):])
    else: para.add_run(text)
    return para
def bullet(text): return doc.add_paragraph(text,style='List Bullet')
def heading(text, level=1): return doc.add_heading(text,level=level)
def code(text):
    para=doc.add_paragraph(); para.paragraph_format.left_indent=Inches(.25); para.paragraph_format.right_indent=Inches(.25); para.paragraph_format.space_after=Pt(8)
    for line in text.strip().splitlines():
        r=para.add_run(line+'\n'); r.font.name='Consolas'; r._element.rPr.rFonts.set(qn('w:eastAsia'),'Consolas'); r.font.size=Pt(8); r.font.color.rgb=RGBColor(40,40,40)
    shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),'F3F5F7'); para._p.get_or_add_pPr().append(shd)
def figure(title, explanation):
    t=doc.add_table(rows=1,cols=1); t.alignment=WD_TABLE_ALIGNMENT.CENTER; c=t.cell(0,0); shade(c,'F4F6F9'); c.width=Inches(6.2); c.text=''
    pr=c.paragraphs[0]; pr.alignment=WD_ALIGN_PARAGRAPH.CENTER; pr.paragraph_format.space_before=Pt(24); pr.paragraph_format.space_after=Pt(24); r=pr.add_run('[ SCREENSHOT PLACEHOLDER ]\n'+title); r.bold=True; r.font.color.rgb=RGBColor.from_string('1F4D78'); r.font.size=Pt(12)
    cap=doc.add_paragraph('Figure '+str(figure.n)+'. '+title+'. '+explanation,style='Caption'); figure.n+=1
figure.n=1
def mermaid(title, source):
    heading(title,3); p('Mermaid source - render in a Mermaid-capable editor if a graphical figure is required by the centre.',boldlead='Mermaid source - '); code(source)
def page_break(): doc.add_page_break()
def add_page_number(paragraph):
    paragraph.alignment=WD_ALIGN_PARAGRAPH.RIGHT
    paragraph.add_run('Fanimation eProject Report | Page ')
    fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'PAGE'); paragraph._p.append(fld)

# Header/footer
header=sec.header.paragraphs[0]; header.text='FANIMATION | ePROJECT REPORT'; header.runs[0].font.size=Pt(8); header.runs[0].font.color.rgb=RGBColor(110,110,110)
add_page_number(sec.footer.paragraphs[0])

# Cover
for _ in range(5): p('')
q=doc.add_paragraph(); q.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=q.add_run('ePROJECT REPORT'); r.bold=True; r.font.size=Pt(14); r.font.color.rgb=RGBColor.from_string('146941')
q=doc.add_paragraph(); q.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=q.add_run('FANIMATION'); r.bold=True; r.font.size=Pt(30); r.font.color.rgb=RGBColor.from_string('0B2545')
q=doc.add_paragraph(); q.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=q.add_run('A React-Based Product Catalogue and Interactive Fan Storefront'); r.font.size=Pt(15); r.font.color.rgb=RGBColor(80,80,80)
p(''); table(['Submission information','Value'],[['Student Name','[Insert student name]'],['Student ID','[Insert student ID]'],['Centre','[Insert centre]'],['Course','[Insert course]'],['Semester','[Insert semester]'],['Session','[Insert academic session]'],['Submission Date','[Insert submission date]']], [2.1,4.1])
p('Prepared as a technical report based on the submitted source code. All statements about implementation reflect the repository inspected for this report.',boldlead='Prepared')
page_break()

# TOC front matter
heading('Table of Contents',1)
p('This Word document contains Heading 1-3 styles and a dynamic Table of Contents field. In Microsoft Word, right-click the table of contents and choose “Update Field” before final submission to refresh page numbers after any edits.')
toc=doc.add_paragraph(); fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'TOC \\o "1-3" \\h \\z \\u'); toc._p.append(fld)
p('Report structure: Acknowledgements; eProject Synopsis; eProject Analysis; eProject Design; diagrams; proposed database design; screenshot plan; source-code commentary; user guide; developer guide; modules; testing; conclusion.',style='Caption')
page_break()

heading('Acknowledgements',1)
p('I acknowledge the guidance of my lecturers, supervisors, and peers whose teaching and feedback supported the completion of this eProject. I also acknowledge the tools and resources used in developing the Fanimation interface. This report has been prepared from the delivered React source code and is intended to present the work accurately and professionally.')

heading('1. eProject Synopsis',1)
heading('1.1 Introduction',2); p('Fanimation is a responsive single-page web application that presents a catalogue of fan products and related accessories. It combines a marketing-style landing page with interactive product discovery, product-detail overlays, favourites, a client-side cart, a gallery, offers, frequently asked questions, and a validated contact form.')
heading('1.2 Background',2); p('The implementation models a consumer-facing fan catalogue. Product records are held locally in JavaScript and rendered in React. The interface communicates pricing in Nigerian naira (N) and includes catalogue categories for ceiling, pedestal, wall and exhaust fans, plus accessories.')
heading('1.3 Purpose and Objectives',2)
for x in ['Present a visually organised fan product catalogue.','Allow users to filter and sort the available products.','Allow users to view richer product details, mark favourites, and manage a temporary cart.','Provide supporting promotional, gallery, company, FAQ and contact sections in one scrollable experience.','Demonstrate a responsive React component architecture using Vite, Bootstrap and custom CSS.']: bullet(x)
heading('1.4 Scope',2); p('The delivered application is front-end only. It renders 15 local product records and images. It does not include authentication, a backend API, database, search behaviour, payment execution, checkout processing, order persistence, or message delivery. The visible Checkout button has no click handler; the contact form validates input and shows a local success state only.')
heading('1.5 Technologies Used',2); table(['Technology','Verified use'],[['React 19','Component rendering and local state.'],['Vite 8','Development server and configured production build tool.'],['Bootstrap 5','Grid, form, button, accordion and responsive utility classes.'],['Lucide React','Interface icons.'],['CSS','Component-scoped stylesheet files plus global smooth-scrolling/focus overrides.'],['JavaScript modules','Catalogue data, components and helper functions.']], [1.5,4.7])
heading('1.6 Expected Outcome',2); p('A visitor can browse a responsive Fanimation storefront, narrow its local product catalogue, inspect products in a modal, manage a temporary cart and use the contact-form interaction. These outcomes are implemented as client-side interactions only.')

heading('2. eProject Analysis',1)
heading('2.1 Existing System',2); p('No separate legacy system is present in the uploaded repository. The delivered application itself is the system available for analysis. It behaves as a static, front-end catalogue and promotional site.')
heading('2.2 Problems Addressed',2); p('The interface addresses the practical discovery problem of presenting multiple fan types in a single catalogue. Category, type, colour, brand, price ceiling and sort controls reduce the effort required to browse the 15 available records.')
heading('2.3 Proposed System',2); p('The proposed and implemented system is a React single-page application. It centralises catalogue information in src/data/products.js, composes the page from reusable modules, and keeps transient user interactions in React state.')
heading('2.4 Functional Requirements - Verified',2)
table(['ID','Requirement','Implementation status / evidence'],[['FR-01','Display a promotional homepage','Implemented: Navbar, Ticker, Hero and Features are rendered by App.'],['FR-02','Browse products','Implemented: ProductGrid maps the filtered local catalogue to cards.'],['FR-03','Filter products','Implemented: category, dependent type, price, colour and brand controls.'],['FR-04','Sort products','Implemented: popular (rating), newest (descending id), price ascending and descending.'],['FR-05','View details','Implemented: ProductCard opens ProductModal.'],['FR-06','Manage favourites','Implemented in memory via favourite product IDs and visible count.'],['FR-07','Manage cart','Implemented in memory: add, quantity +/- and subtotal drawer.'],['FR-08','View promotions and gallery','Implemented: oldPrice-derived offers and eight-image lightbox gallery.'],['FR-09','Read FAQs','Implemented: Bootstrap collapse accordion.'],['FR-10','Contact interaction','Implemented: client-side required/email validation and confirmation state.']], [.65,1.8,3.75])
heading('2.5 Non-functional Requirements - Observed',2)
for x in ['Responsive layout through Bootstrap breakpoints and local media queries.','Smooth anchor scrolling with scroll-margin for section targets.','Basic accessibility measures: semantic sections, labels, alt text and aria-labels on important controls.','Fast local data access because the catalogue and assets are bundled with the client.','Maintainability through independently styled component folders.']: bullet(x)
heading('2.6 Assumptions and Constraints',2); p('Catalogue prices are comma-formatted strings and are converted for comparison and calculation. Delivery, warranty, showroom and company statements are presentation content, not integrated business services. LocalStorage stores a browser-local visitor counter; SessionStorage prevents incrementing it more than once in the current browser session. No persistence is provided for favourites or cart data.')
heading('2.7 Feasibility Analysis',2); table(['Area','Assessment'],[['Technical','Feasible for a demonstrator: the client-only architecture has few infrastructure dependencies.'],['Operational','Usable for browsing and enquiry demonstration; not operationally complete for sales because checkout and contact delivery are absent.'],['Economic','Low running complexity for a static deployment; a production service would require API, database, security and payment costs.'],['Schedule','The component/data separation permits focused incremental enhancement.']], [1.3,5.2])

heading('3. eProject Design',1)
heading('3.1 Overall System Architecture',2); p('The browser loads index.html, which mounts main.jsx into #root. main.jsx imports Bootstrap and global CSS, then renders App. App composes the site sections and owns cross-section favourite, cart and cart-drawer state. ProductSection owns the filter state and derives filtered results from allProducts.')
mermaid('Figure 1. Component and data architecture','''flowchart TD\n  Browser --> index[index.html] --> main[src/main.jsx] --> App\n  App --> Navbar & Ticker & Hero & Features & ProductSection & CartDrawer & Gallery & Offers & About & FAQ & Contact & Footer\n  ProductSection --> ProductFilter & ProductGrid\n  ProductGrid --> ProductCard --> ProductModal\n  Products[(products.js: local array)] --> ProductSection\n  Products --> Gallery\n  Products --> Offers\n  AppState[(favourites/cart state)] --> Navbar\n  AppState --> ProductSection\n  AppState --> CartDrawer''')
heading('3.2 Folder Structure',2); code('''src/\n  assets/images/                 hero, logo and 15 product photos\n  components/                    14 feature/component folders\n    ProductSection/ProductGrid/ProductCard\n  data/products.js               catalogue, allProducts and toNumber\n  styles/global.css              global scroll/focus styling\n  App.jsx                        application composition and shared state\n  main.jsx                       React bootstrap and Bootstrap imports\npublic/                          favicon.svg and icons.svg\npackage.json                     scripts and dependencies\nvite.config.js                   React plugin configuration''')
heading('3.3 Navigation and Application Flow',2); p('Navbar and footer links use in-page anchors. Product-category links dispatch a CustomEvent named fanimation:filter-category; ProductSection listens for it, updates category filter state and the page scrolls to the products section. The Hero button scrolls to products directly. On mobile, Navbar displays an overlay panel controlled by isMenuOpen.')
heading('3.4 State Management',2); table(['State owner','State','Purpose'],[['App','favoriteIds','Array of product IDs; toggled by cards/modal and shown in Navbar.'],['App','cartItems, isCartOpen','Cart records/quantities and drawer visibility.'],['ProductSection','filters','Category, type, price ceiling, colour, brand and sort selection.'],['ProductCard','showModal','Whether its detail modal is rendered.'],['Gallery','activeImage','Selected lightbox image.'],['Contact','form, errors, submitted','Controlled form, validation feedback and local success message.'],['Navbar','visitorCount, isMenuOpen','Browser-local counter and mobile menu visibility.'],['Ticker','now','Live one-second clock.']], [1.4,1.5,3.6])
heading('3.5 Data Flow and Filtering',2); p('allProducts is the authoritative current catalogue. ProductSection derives the maximum price and option lists with useMemo. It filters by exact category/type/colour/brand match and numeric price ceiling. It then sorts a copied result set. Changing category clears a previously selected type because that type may no longer be valid.')
heading('3.6 Styling and Responsive Design',2); p('Bootstrap supplies the container/row/column grid and responsive breakpoints. Each module imports its own CSS file. Gallery changes from four columns to three below 992px and two below 576px. Navbar switches to a mobile overlay at 991px and below. About stats stack at 576px. Modal padding/image size reduce at 576px. Product columns use col-lg-4 col-md-6, producing three columns on large screens and two on medium screens before stacking on small screens.')

heading('4. Data Flow Diagrams, Flowcharts and Process Diagrams',1)
mermaid('4.1 Context Diagram','''flowchart LR\n  U[Visitor] -->|browse, filter, favourite, add to cart, submit contact form| S[Fanimation SPA]\n  S -->|catalogue, UI feedback, local cart/favourite state| U\n  S -->|read/write visitor count| LS[(Browser localStorage/sessionStorage)]\n  D[Bundled product data/assets] --> S\n  note[No API, database, email or payment gateway is connected] -.-> S''')
mermaid('4.2 Level 1 DFD','''flowchart TD\n U[Visitor] --> N[Navigation process]\n U --> P[Catalogue/filter process]\n U --> C[Cart/favourite process]\n U --> F[Contact validation process]\n N --> V[Rendered sections]\n P <--> D[(products.js)]\n P --> V\n C --> M[(React App state)] --> V\n F --> V\n N <--> L[(localStorage/sessionStorage visitor counter)]''')
mermaid('4.3 Level 2 DFD - Catalogue filtering','''flowchart TD\n I[Filter input or category event] --> S[Update filters state]\n S --> T{Category changed?}\n T -->|yes| R[Reset type]\n T -->|no| X[Keep type]\n R --> F[Filter allProducts]\n X --> F\n F --> G[Category/type/colour/brand/price tests]\n G --> O[Sort selected result]\n O --> K[Render ProductGrid or no-results message]''')
mermaid('4.4 Flowchart - Application startup','''flowchart TD\n A[Open site] --> B[index.html loads]\n B --> C[main.jsx imports Bootstrap/global CSS]\n C --> D[createRoot renders App in StrictMode]\n D --> E[Sections and local catalogue render]\n E --> F[Navbar visitor effect and ticker timer begin]''')
mermaid('4.5 Flowchart - Homepage navigation','''flowchart TD\n A[Click nav/footer link] --> B{Category link?}\n B -->|yes| C[Dispatch fanimation:filter-category]\n B -->|no| D[Find target section]\n C --> D --> E[Smooth scroll]\n E --> F[Mobile panel closes when used]''')
mermaid('4.6 Flowchart - Product browsing and filtering','''flowchart TD\n A[Open products] --> B[Show all 15 records sorted by rating]\n B --> C[Choose filter or sort]\n C --> D[Update filters]\n D --> E[Derive matching records]\n E --> F{Any match?}\n F -->|yes| G[Render cards]\n F -->|no| H[Show adjustment message]''')
mermaid('4.7 Flowchart - Product details modal','''flowchart TD\n A[Click View Details] --> B[showModal=true]\n B --> C[Render modal and lock body scroll]\n C --> D{Action}\n D -->|Add to Cart| E[App increments/adds item and opens drawer]\n D -->|Favourite| F[Toggle product ID]\n D -->|Close/backdrop/Escape| G[Unmount modal and restore scroll]''')
mermaid('4.8 Flowchart - Contact process','''flowchart TD\n A[Enter form fields] --> B[Submit]\n B --> C[Prevent default]\n C --> D[Validate name, email and message]\n D --> E{Errors?}\n E -->|yes| F[Display inline errors]\n E -->|no| G[Show success message and clear form]\n G --> H[No transmission occurs in current implementation]''')
mermaid('4.9 Overall user flow','''flowchart LR\n Start --> Home --> Products --> Details --> Cart\n Home --> Gallery\n Home --> Offers --> Products\n Home --> FAQ\n Home --> Contact\n Cart --> End[Checkout button visible; no checkout workflow implemented]''')
mermaid('4.10 Process - Product viewing','''flowchart LR\n Catalogue[products.js] --> Grid[ProductGrid] --> Card[ProductCard] --> Modal[ProductModal]\n Modal --> Info[Image, rating, description, specs, price and perks]''')
mermaid('4.11 Process - Search/filtering','''flowchart LR\n Note[No text-search input/action is implemented] --> Filters[Category/type/price/colour/brand controls] --> Results[Filtered and sorted cards]''')
mermaid('4.12 Process - Modal, navigation, contact and complete workflow','''flowchart TD\n Navigation --> Catalogue --> Modal --> Cart\n Navigation --> Gallery --> Lightbox\n Navigation --> Contact --> Validation --> Confirmation\n Cart --> LocalOnly[Temporary browser state only]''')

heading('5. Database Design / Structure',1)
heading('5.1 Current versus Proposed Design',2); p('Current implementation: no database exists. The catalogue is a static JavaScript array; reviews, ratings and prices are display fields in that array. Browser storage is used only for the visitor counter and session marker. The following is a proposed normalized production design, clearly separate from the delivered implementation.')
mermaid('5.2 Proposed production ER Diagram','''erDiagram\n CATEGORY ||--o{ PRODUCT : classifies\n PRODUCT ||--o{ REVIEW : receives\n USER ||--o{ REVIEW : writes\n USER ||--o{ WISHLIST : owns\n PRODUCT ||--o{ WISHLIST : saved\n USER ||--o{ ORDER : places\n ORDER ||--|{ ORDER_ITEM : contains\n PRODUCT ||--o{ ORDER_ITEM : ordered\n USER ||--o{ CONTACT_MESSAGE : sends\n CATEGORY { int category_id PK\n string name UK\n }\n PRODUCT { int product_id PK\n int category_id FK\n string name\n decimal price\n decimal old_price\n decimal rating\n int review_count\n }\n USER { int user_id PK\n string email UK\n string full_name\n }\n REVIEW { int review_id PK\n int product_id FK\n int user_id FK\n tinyint rating\n text comment\n }\n WISHLIST { int wishlist_id PK\n int user_id FK\n int product_id FK\n }\n ORDER { int order_id PK\n int user_id FK\n decimal subtotal\n string status\n }\n ORDER_ITEM { int order_item_id PK\n int order_id FK\n int product_id FK\n int quantity\n decimal unit_price\n }\n CONTACT_MESSAGE { int message_id PK\n int user_id FK\n string name\n string email\n text message\n }''')
heading('5.3 Proposed Table Structures and Constraints',2)
table(['Table','Key fields and types','Constraints/relationships'],[['categories','category_id INT PK; name VARCHAR(80)','name UNIQUE, NOT NULL.'],['products','product_id INT PK; category_id INT FK; name VARCHAR(180); type VARCHAR(120); colour VARCHAR(60); brand VARCHAR(80); price DECIMAL(12,2); old_price DECIMAL(12,2) NULL; rating DECIMAL(2,1); description TEXT','price >= 0; old_price > price when supplied; belongs to one category.'],['users','user_id INT PK; full_name VARCHAR(120); email VARCHAR(254)','email UNIQUE; required for account-based features.'],['reviews','review_id INT PK; product_id INT FK; user_id INT FK; rating TINYINT; comment TEXT','rating between 1 and 5; one product and one author.'],['contact_messages','message_id INT PK; user_id INT FK NULL; name VARCHAR(120); email VARCHAR(254); message TEXT; created_at TIMESTAMP','name/email/message required; optional linked user.'],['wishlists','wishlist_id INT PK; user_id INT FK; product_id INT FK; created_at TIMESTAMP','UNIQUE(user_id, product_id).'],['orders','order_id INT PK; user_id INT FK; subtotal DECIMAL(12,2); status VARCHAR(30); created_at TIMESTAMP','subtotal >= 0; belongs to one user.'],['order_items','order_item_id INT PK; order_id INT FK; product_id INT FK; quantity INT; unit_price DECIMAL(12,2)','quantity > 0; preserves price at time of order.']], [1.1,3.05,2.85])
heading('5.4 Normalization',2); p('The proposed schema is in third normal form: categories are separated from products; user identity is separated from reviews, wishlist rows and orders; and order lines hold the repeatable product/quantity relationship. Prices in order_items intentionally preserve transactional history rather than relying on a future products.price value.')

heading('6. Screenshot Placeholders',1)
p('The following figure placeholders identify the recommended screenshots for a final submission. Capture them from the running application at the stated viewport before inserting. The source repository contains no submitted screenshots.')
for title,desc in [('Homepage and Hero Banner','Top bar, navigation, hero message and Explore Collection call to action.'),('Navigation and Mobile Menu','Desktop navigation plus the overlay panel at a narrow viewport.'),('Product Catalogue','Filter sidebar, product cards, product count and benefit panel.'),('Product Filters','Category, type, price slider, colour chips, brand and clear action.'),('Product Details Modal','Product image, specifications, rating, add-to-cart and wishlist actions.'),('Cart Drawer','Temporary cart line item, quantity controls and subtotal.'),('Gallery','Eight-image responsive gallery and selected-image lightbox.'),('Offers','Products having oldPrice with calculated percentage discount.'),('About and FAQ','Company text/stat cards and Bootstrap accordion.'),('Contact and Footer','Contact details, validated form, confirmation state and footer links.'),('Tablet View','Bootstrap medium-width arrangement with two product columns.'),('Mobile View','Small-screen stacked product layout and mobile navigation.')]: figure(title,desc)

heading('7. Source Code with Comments',1)
heading('7.1 Commenting Approach',2); p('The reviewed source already includes focused comments around non-obvious behaviour, notably price conversion, category-event communication, modal lifecycle handling, gallery asset reuse and contact-form limitations. The code is not over-commented. The snippets below explain the important logic without rewriting the full source.')
heading('7.2 Shared Cart State - App.jsx',2); code('''const handleAddToCart = (product) => {\n  const normalizedProduct = { ...product,\n    name: product?.name || product?.title || "Product",\n    price: toNumber(product?.price ?? product?.cost ?? product?.amount ?? 0),\n  };\n  setCartItems((prev) => {\n    const existing = prev.find((item) => item.id === normalizedProduct.id);\n    if (existing) return prev.map((item) =>\n      item.id === normalizedProduct.id\n        ? { ...item, quantity: item.quantity + 1 } : item);\n    return [...prev, { ...normalizedProduct, quantity: 1 }];\n  });\n  setIsCartOpen(true);\n};'''); p('This function normalizes flexible product-like inputs, increments an existing cart line or appends a new one, then opens the drawer. It is held in App so Navbar, ProductSection and CartDrawer can share the same state.')
heading('7.3 Derived Filtering - ProductSection.jsx',2); code('''let result = allProducts.filter((product) => {\n  if (filters.category && product.category !== filters.category) return false;\n  if (filters.type && product.type !== filters.type) return false;\n  if (filters.color && product.color !== filters.color) return false;\n  if (filters.brand && product.brand !== filters.brand) return false;\n  if (filters.price && toNumber(product.price) > Number(filters.price)) return false;\n  return true;\n});\n// result is then copied and sorted by rating, id or numeric price.'''); p('The predicate only applies a criterion when its filter value is present. toNumber removes commas from stored price strings before numeric comparison.')
heading('7.4 Modal Lifecycle - ProductModal.jsx',2); code('''useEffect(() => {\n  const handleKeyDown = (e) => { if (e.key === "Escape") onClose(); };\n  document.addEventListener("keydown", handleKeyDown);\n  document.body.style.overflow = "hidden";\n  return () => {\n    document.removeEventListener("keydown", handleKeyDown);\n    document.body.style.overflow = "";\n  };\n}, [onClose]);'''); p('When mounted, the modal listens for Escape and disables page scrolling. Its cleanup restores both; backdrop clicks call onClose while clicks within the modal stop propagation.')
heading('7.5 Contact Validation - Contact.jsx',2); code('''const validate = (values) => {\n  const nextErrors = {};\n  if (!values.name.trim()) nextErrors.name = "Please enter your name.";\n  if (!values.email.trim()) nextErrors.email = "Please enter your email.";\n  else if (!/^\\S+@\\S+\\.\\S+$/.test(values.email))\n    nextErrors.email = "Please enter a valid email address.";\n  if (!values.message.trim()) nextErrors.message = "Please enter a message.";\n  return nextErrors;\n};'''); p('The validation runs entirely in the browser. A valid submission clears the fields and displays a confirmation but does not send or store a message.')

heading('8. User Guide',1)
heading('8.1 Introduction and System Requirements',2); p('Fanimation is used through a modern web browser with JavaScript enabled. No user account is required for the current demonstrator. Internet access is only needed when the app is deployed or served remotely; the submitted source can run locally with Node.js and npm.')
heading('8.2 Starting the Application',2); p('A non-technical user normally opens the deployed site in a browser. For a local demonstration, a developer starts the Vite development server; then the user opens the displayed local address.')
heading('8.3 Using the Homepage and Navigation',2); p('Use the navigation bar or footer links to jump to a section. Choose a product-category link such as CEILING FANS to move to the catalogue with that category already selected. On a narrow screen, use the hamburger button to open the navigation panel. The Explore Collection button moves to products.')
heading('8.4 Browsing, Filtering and Sorting Products',2); p('At Products, use Category, Type, Price Range, Color and Brand controls. Colour circles toggle a colour selection. Choose a Sort By option to change the order. Use Clear Filters to return to all categories, all types/colours/brands, the maximum price and Popular sort. If nothing matches, the page says to adjust or clear filters.')
heading('8.5 Product Details, Favourites and Cart',2); p('Select View Details to open a product modal. Read the specifications and price, then choose Add to Cart or the heart button. Close using the X, by clicking outside the panel, or pressing Escape. The cart icon opens the cart drawer. Use minus/plus buttons to change quantities; reducing a line from one to zero removes it. Checkout is presently a visual button only and does not complete a purchase.')
heading('8.6 Gallery, Offers, FAQs and Contact',2); p('Select a gallery image to enlarge it; click the overlay to close. Offers show the items whose local data has an old price. Expand FAQ questions to read their answers. In Contact, enter a name, a syntactically valid email and a message; submit to receive a local confirmation. The message is not sent to an organisation in the current version.')
heading('8.7 Troubleshooting and Closing',2); table(['Issue','Action'],[['Product list appears empty','Use Clear Filters.'],['Modal will not close','Press Escape, click the close X, or click outside the panel.'],['Cart contents disappear','This is expected after a page refresh because cart state is not persisted.'],['Contact confirmation expected by email','The app does not transmit email; the confirmation is visual only.'],['Close the site','Close the browser tab. For local hosting, stop the Vite terminal with Ctrl+C.']], [2.2,4.8])

heading('9. Developer Guide',1)
heading('9.1 Installation and Commands',2); code('''npm install\nnpm run dev\nnpm run build\nnpm run preview\nnpm run lint'''); p('package.json defines these scripts. The project uses ESM ("type": "module"). Vite configuration registers only the React plugin. Bootstrap CSS and bundle JS are imported at startup so the FAQ collapse behaviour is available.')
heading('9.2 Component Hierarchy and Dependencies',2); p('App is the composition root. ProductSection depends on ProductFilter and ProductGrid; ProductGrid depends on ProductCard; ProductCard conditionally renders ProductModal. App also imports CartDrawer. Components import their paired CSS and Lucide icons where required. allProducts is read by ProductSection, Gallery and Offers.')
heading('9.3 Adding or Editing a Product',2); p('Edit src/data/products.js. Add an object with a unique numeric id, name, category, type, color, brand, comma-formatted price, rating, reviews, badge (if needed), imported image and description. oldPrice is optional; when present it causes Offers to include that record. Add a corresponding colour mapping in ProductSection.jsx if a new colour should show as an accurate filter swatch.')
heading('9.4 Extending Features',2); p('For persistence, replace local arrays with an API-backed data layer and move cart/favourites to authenticated server state or local storage. For functional contact, submit to a secure endpoint and surface asynchronous failure/success. For checkout, add a verified payment flow, server-side price calculation and order creation. Text search is not implemented and should be designed as a separate filter criterion rather than describing the present filter UI as search.')
heading('9.5 Styling, Debugging and Maintenance',2); p('Keep reusable styles within the component folder and reserve global.css for truly global rules. Preserve Bootstrap breakpoint classes where the layout depends on them. Verify modal cleanup, category-event listener cleanup and timer cleanup after changes. Use the Vite console and browser developer tools for runtime issues. Keep product price display and numeric conversion compatible, or migrate prices to numeric values at the API boundary.')
heading('9.6 Build and Deployment',2); p('The intended build command is npm run build, which invokes vite build and normally emits a deployable bundle to dist. During this report’s verification, the installed dependency set produced a Vite/Rolldown build error concerning an absolute/relative emitted index.html name. Resolve that environment/dependency issue and rerun the build before deploying; do not treat the existing dist directory as proof that the present build passes.')

heading('10. Module Descriptions',1)
table(['Module','Purpose, inputs/outputs and key relationships'],[['main.jsx','Imports Bootstrap/global CSS and mounts App in React StrictMode.'],['App.jsx','Top-level composition; owns favourites, cart and cart-drawer state; passes callbacks/counts.'],['Navbar','Anchor navigation, category CustomEvent dispatch, visitor counter, mobile overlay, favourite/cart indicators.'],['Ticker','Scrolling announcements and one-second display clock.'],['Hero','Hero asset, marketing content and scroll-to-products action.'],['Features','Four static feature cards.'],['ProductSection','Filter state, option derivation, CustomEvent listener, filtering/sorting and catalogue layout.'],['ProductFilter','Controlled filter controls; returns changes to ProductSection.'],['ProductGrid','Maps matching records to cards or shows no-results state.'],['ProductCard','Renders a product summary, favourite action and per-card modal state.'],['ProductModal','Displays detail; manages Escape/body-scroll lifecycle; triggers cart/favourite callbacks.'],['CartDrawer','Normalizes cart rows, calculates subtotal and exposes quantity/close actions.'],['Gallery','Derives first eight product images and controls a lightbox.'],['Offers','Selects oldPrice records and calculates percentage reductions.'],['About','Static company narrative and four statistics.'],['FAQ','Static FAQ data in Bootstrap accordion markup.'],['Contact','Controlled validation form and local confirmation state.'],['Footer','Static links, category filter dispatch and contact/social presentation.'],['products.js','15 local records; named allProducts and toNumber exports; default first-three subset.'],['CSS files','Component styling, motion and local responsive overrides.']], [1.55,5.45])

heading('11. Testing',1)
heading('11.1 Verification Performed',2); p('The source was inspected module-by-module and the configured build and lint commands were executed in the delivered workspace. No automated test suite is declared in package.json and no test files were found. Therefore, the functional/UI cases below are documented as manual test cases derived from code review and intended browser verification; they are not represented as an invented automated test run.')
table(['Test ID','Test case','Expected result','Actual / status'],[['T-01','Load page','All sections render in page order.','Code-reviewed; implementation present.'],['T-02','Choose a category navigation link','Products section scrolls and category filter updates.','Code-reviewed; CustomEvent/listener present.'],['T-03','Apply filters/sort','Only matching product cards display in requested order.','Code-reviewed; predicate/sort logic present.'],['T-04','Open/close details','Modal opens; X/backdrop/Escape close it and restore scroll.','Code-reviewed; lifecycle present.'],['T-05','Add/adjust cart item','Item is added/incremented; zero quantity removes it; subtotal updates.','Code-reviewed; state logic present.'],['T-06','Submit invalid contact form','Inline errors appear.','Code-reviewed; validate() present.'],['T-07','Submit valid contact form','Confirmation displays and fields clear; no message transmission.','Code-reviewed; local behaviour present.'],['T-08','Responsive UI','Grid/menu/modal changes at defined breakpoints.','Static CSS/Bootstrap review complete; browser matrix not executed.'],['T-09','npm run build','Production bundle should build.','Failed in inspected environment: Vite/Rolldown emitted-name error.'],['T-10','npm run lint','No lint errors expected.','Failed: react-hooks/set-state-in-effect in Navbar.jsx line 40.']], [.55,1.4,2.2,2.85])
heading('11.2 UI, Responsive, Cross-browser and Performance Testing',2); p('The project includes responsive rules but no committed device/browser test evidence or performance benchmark. Recommended completion testing is Chrome, Firefox, Edge and Safari at desktop, tablet and mobile widths; validate navigation, FAQ collapse, modal, lightbox, cart and contact states. Production performance should be measured only after the build failure has been resolved.')
heading('11.3 Bugs and Fixes / Observations',2); p('Observed build issue: vite build failed with a Rolldown error that an emitted index.html name was treated as an absolute/relative path. Observed lint issue: Navbar sets visitorCount synchronously in an effect, which the configured React Hooks lint rule rejects. These are report findings, not unverified claims that fixes have been applied. A functional limitation is that social anchors use # and do not target external social destinations.')

heading('12. Conclusion and Future Improvements',1)
heading('12.1 Objectives Achieved',2); p('The delivered project successfully demonstrates a coherent responsive React catalogue experience with 15 products, multi-criterion filtering, sorting, product-modal details, favourites, a temporary cart, gallery, offers, FAQ and contact validation. Its folder structure and local data model make the interface understandable and extendable.')
heading('12.2 Challenges and Lessons Learned',2); p('The project highlights the distinction between a convincing front-end interaction and a production transaction system. Local component state is effective for demonstration but is not durable. Storing formatted prices as strings also requires deliberate conversion before filtering and calculations. Cross-component interactions are managed by lifted state and a small custom browser event, avoiding a global state library.')
heading('12.3 Recommendations and Future Enhancements',2)
for x in ['Resolve the current build/lint findings and add automated component and end-to-end tests.','Add a backend API and normalized database based on the proposed schema.','Persist users, favourites, carts, contact messages and orders securely.','Implement authenticated checkout, payment integration, server-side price validation and order history.','Implement an actual product text search if required; it is not present now.','Add accessible keyboard/focus management for custom overlays, and conduct formal cross-browser/performance testing.','Replace placeholder company/contact information and capture final screenshots after deployment.']: bullet(x)
heading('12.4 Documentation Standards',2); p('This report distinguishes verified implementation from recommended production work. It does not claim backend services, persistence, payment, search or message delivery where the submitted source does not implement them. Before submission, the student should replace cover-page placeholders, update the automatic Table of Contents in Word, insert the numbered running-application screenshots and rerun build/lint after correcting the reported issues.')

# Set field update on opening.
settings=doc.settings.element; update=OxmlElement('w:updateFields'); update.set(qn('w:val'),'true'); settings.append(update)
doc.core_properties.title='Fanimation eProject Report'; doc.core_properties.subject='Technical documentation based on submitted source code'; doc.core_properties.author='[Student Name]'
doc.save(DOCX)
print(DOCX)
